mysite/createprofile/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'createprofile'
urlpatterns = [
    url(r'^employer/$', views.emplyer_create_profile, name='emplyer_create_profile'),
    url(r'^employer/edit/$', views.emplyer_edit_profile, name='emplyer_edit_profile'),
    url(r'^employer/home/$', views.employer_home, name='employer_home'),
    url(r'^employer/uploadlisting/$', views.listing_form_upload, name='listing_form_upload'),
    url(r'^employer/uploadlogo/$', views.employer_photo_form_upload, name='employer_photo_form_upload'),
    url(r'^employer/view_profile/$', views.employer_view_profile, name='employer_view_profile'),

    url(r'^employee/$', views.index, name='index'),
    url(r'^employee/edit/$', views.emplyee_edit_profile, name='emplyee_edit_profile'),
    url(r'^employee/home/$', views.employee_home, name='employee_home'),
    url(r'^employee/view_profile/$', views.employee_view_profile, name='employee_view_profile'),
    url(r'^employee/uploadcv/$', views.model_form_upload, name='model_form_upload'),
    url(r'^employee/uploadpp/$', views.photo_form_upload, name='photo_form_upload'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/createprofile/templates/createprofile/employee_edit_profile.html
<h2>Welcome, {{ user.username }}!</h2>
<p>Want to go back to your home page?</p>
<a href="{% url 'createprofile:employee_home' %}">Take me home</a>
{% block content %}
  <h2>Come and Edit your profile</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

mysite/createprofile/templates/createprofile/employee_home.html
  <header>
    <h1>Employee Home Page</h1>
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a>
    {% endif %}
  </header>
<p> You are now on the employee home page</p>
<p>How about starting to create your profile?</p>
<a href="{% url 'createprofile:index' %}">Create profile</a>

 <p>Want to Upload your cv?</p>
<a href="{% url 'createprofile:model_form_upload' %}">Upload CV</a>

 <p>Or your profile pic??</p>
<a href="{% url 'createprofile:photo_form_upload' %}">Upload PP</a>

<p>How about Viewing your profile?</p>
 <a href="{% url 'createprofile:employee_view_profile' %}">view profile</a>
 <p>Already Done?</p>
 <p>How about editing your profile?</p>
 <a href="{% url 'createprofile:emplyee_edit_profile' %}">edit profile</a>

mysite/createprofile/templates/createprofile/employee_view_profile.html
<p>Hi {{u.user}} you are now viewing your profile </p>
<p>Want to go back to your home page?</p>
<a href="{% url 'createprofile:employee_home' %}">Take me home</a>


{% load static %}
{% if image %}
{%for im in image %}
<div>
<img src="{{ im.photo.url }}" alt = "poes" width = "300" height="200">
</div>
{% endfor %}
{% else %}
<div>
<img src="{% static 'createprofile/images/default_images/default_profile_pic.jpg' %}" alt = "poes" width = "300" height="200">
</div>
{% endif %}

<table style="width:100%">
{% for name, value in u_stats.get_fields %}
	<tr>
    	<td>{{ name }}</td>
    	<td>{{ value }}</td>
    </tr>
{% endfor %}
</table>

{% for doc in doc_stats %}
<p> CV Dates </p>
<p> {{doc.uploaded_at}}</p>
{% endfor %}

mysite/createprofile/templates/createprofile/employer_home.html
  <header>
    <h1>Employer Home Page</h1>
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a>
    {% endif %}
  </header>
<p> You are now on the employee home page</p>
<p>How about starting to create your profile?</p>
<a href="{% url 'createprofile:emplyer_create_profile' %}">Create profile</a>

 <p>Want to Upload a listing?</p>
<a href="{% url 'createprofile:listing_form_upload' %}">Upload Listing</a>

 <p>Or your Logo??</p>
<a href="{% url 'createprofile:employer_photo_form_upload' %}">Upload Logo</a>

<p>How about Viewing your profile?</p>
 <a href="{% url 'createprofile:employer_view_profile' %}">view profile</a>
 <p>Already Done?</p>
 <p>How about editing your profile?</p>
 <a href="{% url 'createprofile:emplyer_edit_profile' %}">edit profile</a>

mysite/createprofile/templates/createprofile/employer_view_profile.html
<p>Hi {{u_stats.user}} you are now viewing your profile </p>
<p>Want to go back to your home page?</p>

<a href="{% url 'createprofile:employer_home' %}">Take me home</a>

	


{%for im in image %}
<div>
<img src="{{ im.photo.url }}" alt = "poes" width = "300" height="200">
</div>
{% endfor %}


<table style="width:100%">
{% for name, value in u_stats.get_fields %}
	<tr>
    	<td>{{ name }}</td>
    	<td>{{ value }}</td>
    </tr>
{% endfor %}
</table>

{% for doc in doc_stats %}
<p> Listing Dates </p>
<p> {{doc.uploaded_at}}</p>
{% endfor %}

mysite/createprofile/templates/createprofile/emplyer_create_profile.html
<h2>Welcome, {{ user.username }}!</h2>
{% block content %}
  <h2>Create</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

mysite/createprofile/templates/createprofile/emplyer_edit_profile.html
<h2>Welcome, {{ user.username }}!</h2>
{% block content %}
  <h2>Edit</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

mysite/createprofile/templates/createprofile/index.html
<h2>Welcome, {{ user.username }}!</h2>
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

mysite/createprofile/templates/createprofile/listing_form_upload.html
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <a href="{% url 'createprofile:employer_home' %}">Take me home</a>
{% endblock %}

mysite/createprofile/templates/createprofile/model_form_upload.html
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <a href="{% url 'createprofile:employee_home' %}">Take me home</a>
{% endblock %}

mysite/createprofile/templates/createprofile/simple_upload.html
{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}